version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: hsr_scanner_db
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: cJYVjPL7bDerzaG3
      POSTGRES_DB: hsr_scanner_db

    volumes:
      - db_data:/var/lib/postgresql/data



volumes:
  db_data: