version: '3.9'

services:
  db:
    image: postgres
    restart: always
    container_name: hsr_scanner_db
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: hsr_scanner_db

    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: