name: CI/CD Pipeline

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: mumaw/hsr-scanner-server:latest

      - name: Deploy to vultr
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            # Pull the latest Docker image
            docker pull mumaw/hsr-scanner-server:latest
            
            # Stop the existing container if it exists
            docker stop hsr-scanner-server || true
            
            # Remove the existing container if it exists
            docker rm hsr-scanner-server || true
            
            # Run the new container with volume binding for static files
            docker run -d \
              --name hsr-scanner-server \
              -p 8000:8000 \
              -v /home/ubuntu/static/:/app/static/ \
              mumaw/hsr-scanner-server:latest
            
            # Prune all unused Docker images
            docker image prune -a -f || true